services:
  web:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8001:8000"
    environment:
      - MONGO_HOSTNAME=mongodb
      - test=${REFRESH_TOKEN}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata: