openapi: '3.0.2'
info:
  title: Upload Service
  description: Microservicio de subida de imágenes.
  version: '1.0'
servers:
  - url: https://localhost:8000/
paths:

  /asset:
     get:
       summary: "Returns a list with all the assets in the database."
       responses:
        '200':
          description: Everything went OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/assets"
     post:
       summary: "Add a new asset to the database."
       requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createModifyAsset"
       responses:
         '201':
           description: "The asset was correctly created. The URI of the new asset is in the Location header."
           content:
            application/json:
              schema:
                $ref: "#/components/schemas/assets"
         "400":
            description: "Bad request. One or more input fields are not a string or they are whitespace."
            content:
             application/json:
              schema:
                $ref: "#/components/schemas/notValid"

  /asset/{id}:
    get:
      parameters:
      - Schema:
        $ref: "#/components/parameters/paramId"
      summary: "Devuelve la imagen requerida de la base de datos"
      responses:
        '200':
          description: Todo ha ido correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/asset"
        "400":
          description: "El id de la imagen no es válido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notValid"

        '404':
          description: No se ha encontrado la imagen con el id dado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
    put:
      summary: "Actualiza una imágen existente en la base de datos"
      parameters:
      - Schema:
        $ref: "#/components/parameters/paramId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createModifyAsset"
      responses:
        '200':
          description: Todo ha ido correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/successful"
        "400":
          description: "El id de la imagen no es válido"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notValid"
        "404":
          description: No se ha encontrado la imagen con el id dado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
        # "405":
        #   description: "Validation exception"
    delete:
      summary: "Deletes an asset from the database."
      parameters:
      - Schema:
        $ref: "#/components/parameters/paramId"
      responses:
        '204':
          description: "No content. The asset was correctly deleted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/successful"
        "404":
          description: "Not found. An asset with the specified id could not be found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notFound"
components:
  parameters:
    paramId:
      description: Id de la imagen sobre la que hacer la operación
      name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/paramId"
  schemas:
    paramId:
      type: string
      description: Id de la imagen
    successful:
      type: string
      description: La operación se ha realizado correctamente
    notFound:
      type: string
      description: Imagen no encontrada
    notValid:
      type: string
      description: El id no es válido
    createModifyAsset:
      type: object
      properties:
        file:
          type: string
          description: URL de la imagen almacenada en Google Images
        name:
          type: string
          description: Nombre de la imagen
        user:
          type: string
          description: Usuario al que pertenece la imagen
    asset:
      type: object
      properties:
        _id:
          type: string
          description: Id de la imagen almacenado en la BD
        file:
          type: string
          description: URL de la imagen almacenada en Google Images
        name:
          type: string
          description: Nombre de la imagen
        user:
          type: string
          description: Usuario al que pertenece la imagen
        createdAt:
          type: string
          description: Fecha de creación de la imagen en la BD
        updatedAt:
          type: string
          description: Fecha de actualización de la imagen en la BD
        __v:
          type: integer
          description: Versión de la imagen
    assets:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
            description: Id de la imagen almacenado en la BD
          file:
            type: string
            description: URL de la imagen almacenada en Google Images
          name:
            type: string
            description: Nombre de la imagen
          user:
            type: string
            description: Usuario al que pertenece la imagen
          createdAt:
            type: string
            description: Fecha de creación de la imagen en la BD
          updatedAt:
            type: string
            description: Fecha de actualización de la imagen en la BD
          __v:
            type: integer
            description: Versión de la imagen