apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "upload.labels" . | nindent 4 }}
type: Opaque
data:
  upload_mongo_url: {{ .Values.uploadMongoUrl | b64enc }}